# generated by datamodel-codegen:
#   filename:  https://developer.spotify.com/reference/web-api/open-api-schema.yaml
#   timestamp: 2026-07-03T18:43:55+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class TrackRestrictionObject(BaseModel):
    reason: Annotated[
        str | None,
        Field(
            description="The reason for the restriction. Supported values:\n- `market` - The content item is not available in the given market.\n- `product` - The content item is not available for the user's subscription type.\n- `explicit` - The content item is explicit and the user's account is set to not play explicit content.\n\nAdditional reasons may be added in the future.\n**Note**: If you use this field, make sure that your application safely handles unknown values.\n"
        ),
    ] = None


class Reason(str, Enum):
    market = "market"
    product = "product"
    explicit = "explicit"


class AlbumRestrictionObject(BaseModel):
    reason: Annotated[
        Reason | None,
        Field(
            description="The reason for the restriction. Albums may be restricted if the content is not available in a given market, to the user's subscription type, or when the user's account is set to not play explicit content.\nAdditional reasons may be added in the future.\n"
        ),
    ] = None


class EpisodeRestrictionObject(BaseModel):
    reason: Annotated[
        str | None,
        Field(
            description="The reason for the restriction. Supported values:\n- `market` - The content item is not available in the given market.\n- `product` - The content item is not available for the user's subscription type.\n- `explicit` - The content item is explicit and the user's account is set to not play explicit content.\n\nAdditional reasons may be added in the future.\n**Note**: If you use this field, make sure that your application safely handles unknown values.\n"
        ),
    ] = None


class ChapterRestrictionObject(BaseModel):
    reason: Annotated[
        str | None,
        Field(
            description="The reason for the restriction. Supported values:\n- `market` - The content item is not available in the given market.\n- `product` - The content item is not available for the user's subscription type.\n- `explicit` - The content item is explicit and the user's account is set to not play explicit content.\n- `payment_required` - Payment is required to play the content item.\n\nAdditional reasons may be added in the future.\n**Note**: If you use this field, make sure that your application safely handles unknown values.\n"
        ),
    ] = None


class Type(str, Enum):
    artist = "artist"


class DisallowsObject(BaseModel):
    interrupting_playback: Annotated[
        bool | None, Field(description="Interrupting playback. Optional field.")
    ] = None
    pausing: Annotated[bool | None, Field(description="Pausing. Optional field.")] = (
        None
    )
    resuming: Annotated[bool | None, Field(description="Resuming. Optional field.")] = (
        None
    )
    seeking: Annotated[
        bool | None, Field(description="Seeking playback location. Optional field.")
    ] = None
    skipping_next: Annotated[
        bool | None, Field(description="Skipping to the next context. Optional field.")
    ] = None
    skipping_prev: Annotated[
        bool | None,
        Field(description="Skipping to the previous context. Optional field."),
    ] = None
    toggling_repeat_context: Annotated[
        bool | None, Field(description="Toggling repeat context flag. Optional field.")
    ] = None
    toggling_shuffle: Annotated[
        bool | None, Field(description="Toggling shuffle flag. Optional field.")
    ] = None
    toggling_repeat_track: Annotated[
        bool | None, Field(description="Toggling repeat track flag. Optional field.")
    ] = None
    transferring_playback: Annotated[
        bool | None,
        Field(description="Transfering playback between devices. Optional field."),
    ] = None


class ErrorObject(BaseModel):
    status: Annotated[
        int,
        Field(
            description="The HTTP status code (also returned in the response header; see [Response Status Codes](/documentation/web-api/concepts/api-calls#response-status-codes) for more information).\n",
            ge=400,
            le=599,
        ),
    ]
    message: Annotated[
        str, Field(description="A short description of the cause of the error.\n")
    ]


class Type2(str, Enum):
    user = "user"


class Meta(BaseModel):
    analyzer_version: Annotated[
        str | None,
        Field(
            description="The version of the Analyzer used to analyze this track.",
            examples=["4.0.0"],
        ),
    ] = None
    platform: Annotated[
        str | None,
        Field(
            description="The platform used to read the track's audio data.",
            examples=["Linux"],
        ),
    ] = None
    detailed_status: Annotated[
        str | None,
        Field(
            description="A detailed status code for this track. If analysis data is missing, this code may explain why.",
            examples=["OK"],
        ),
    ] = None
    status_code: Annotated[
        int | None,
        Field(
            description="The return code of the analyzer process. 0 if successful, 1 if any errors occurred.",
            examples=[0],
        ),
    ] = None
    timestamp: Annotated[
        int | None,
        Field(
            description="The Unix timestamp (in seconds) at which this track was analyzed.",
            examples=[1495193577],
        ),
    ] = None
    analysis_time: Annotated[
        float | None,
        Field(
            description="The amount of time taken to analyze this track.",
            examples=[6.93906],
        ),
    ] = None
    input_process: Annotated[
        str | None,
        Field(
            description="The method used to read the track's audio data.",
            examples=["libvorbisfile L+R 44100->22050"],
        ),
    ] = None


class TimeIntervalObject(BaseModel):
    start: Annotated[
        float | None,
        Field(
            description="The starting point (in seconds) of the time interval.",
            examples=[0.49567],
        ),
    ] = None
    duration: Annotated[
        float | None,
        Field(
            description="The duration (in seconds) of the time interval.",
            examples=[2.18749],
        ),
    ] = None
    confidence: Annotated[
        float | None,
        Field(
            description="The confidence, from 0.0 to 1.0, of the reliability of the interval.",
            examples=[0.925],
            ge=0.0,
            le=1.0,
        ),
    ] = None


class Mode1(float, Enum):
    number__1 = -1
    number_0 = 0
    number_1 = 1


class Pitch(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=1.0)]


class SegmentObject(BaseModel):
    start: Annotated[
        float | None,
        Field(
            description="The starting point (in seconds) of the segment.",
            examples=[0.70154],
        ),
    ] = None
    duration: Annotated[
        float | None,
        Field(
            description="The duration (in seconds) of the segment.", examples=[0.19891]
        ),
    ] = None
    confidence: Annotated[
        float | None,
        Field(
            description="The confidence, from 0.0 to 1.0, of the reliability of the segmentation. Segments of the song which are difficult to logically segment (e.g: noise) may correspond to low values in this field.\n",
            examples=[0.435],
            ge=0.0,
            le=1.0,
        ),
    ] = None
    loudness_start: Annotated[
        float | None,
        Field(
            description='The onset loudness of the segment in decibels (dB). Combined with `loudness_max` and `loudness_max_time`, these components can be used to describe the "attack" of the segment.',
            examples=[-23.053],
        ),
    ] = None
    loudness_max: Annotated[
        float | None,
        Field(
            description='The peak loudness of the segment in decibels (dB). Combined with `loudness_start` and `loudness_max_time`, these components can be used to describe the "attack" of the segment.',
            examples=[-14.25],
        ),
    ] = None
    loudness_max_time: Annotated[
        float | None,
        Field(
            description='The segment-relative offset of the segment peak loudness in seconds. Combined with `loudness_start` and `loudness_max`, these components can be used to desctibe the "attack" of the segment.',
            examples=[0.07305],
        ),
    ] = None
    loudness_end: Annotated[
        float | None,
        Field(
            description="The offset loudness of the segment in decibels (dB). This value should be equivalent to the loudness_start of the following segment.",
            examples=[0.0],
        ),
    ] = None
    pitches: Annotated[
        list[Pitch] | None,
        Field(
            description="Pitch content is given by a “chroma” vector, corresponding to the 12 pitch classes C, C#, D to B, with values ranging from 0 to 1 that describe the relative dominance of every pitch in the chromatic scale. For example a C Major chord would likely be represented by large values of C, E and G (i.e. classes 0, 4, and 7).\n\nVectors are normalized to 1 by their strongest dimension, therefore noisy sounds are likely represented by values that are all close to 1, while pure tones are described by one value at 1 (the pitch) and others near 0.\nAs can be seen below, the 12 vector indices are a combination of low-power spectrum values at their respective pitch frequencies.\n![pitch vector](/assets/audio/Pitch_vector.png)\n",
            examples=[[0.212, 0.141, 0.294]],
        ),
    ] = None
    timbre: Annotated[
        list[float] | None,
        Field(
            description="Timbre is the quality of a musical note or sound that distinguishes different types of musical instruments, or voices. It is a complex notion also referred to as sound color, texture, or tone quality, and is derived from the shape of a segment’s spectro-temporal surface, independently of pitch and loudness. The timbre feature is a vector that includes 12 unbounded values roughly centered around 0. Those values are high level abstractions of the spectral surface, ordered by degree of importance.\n\nFor completeness however, the first dimension represents the average loudness of the segment; second emphasizes brightness; third is more closely correlated to the flatness of a sound; fourth to sounds with a stronger attack; etc. See an image below representing the 12 basis functions (i.e. template segments).\n![timbre basis functions](/assets/audio/Timbre_basis_functions.png)\n\nThe actual timbre of the segment is best described as a linear combination of these 12 basis functions weighted by the coefficient values: timbre = c1 x b1 + c2 x b2 + ... + c12 x b12, where c1 to c12 represent the 12 coefficients and b1 to b12 the 12 basis functions as displayed below. Timbre vectors are best used in comparison with each other.\n",
            examples=[[42.115, 64.373, -0.233]],
        ),
    ] = None


class TimeSignature(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description='An estimated time signature. The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure). The time signature ranges from 3 to 7 indicating time signatures of "3/4", to "7/4".',
            examples=[4],
            ge=3,
            le=7,
        ),
    ]


class Tempo(RootModel[float]):
    root: Annotated[
        float,
        Field(
            description="The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.\n",
            examples=[118.211],
        ),
    ]


class Loudness(RootModel[float]):
    root: Annotated[
        float,
        Field(
            description="The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track and are useful for comparing relative loudness of tracks. Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typically range between -60 and 0 db.\n",
            examples=[-5.883],
        ),
    ]


class Key(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description="The key the track is in. Integers map to pitches using standard [Pitch Class notation](https://en.wikipedia.org/wiki/Pitch_class). E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on. If no key was detected, the value is -1.\n",
            examples=[9],
            ge=-1,
            le=11,
        ),
    ]


class Mode(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description="Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0.\n",
            examples=[0],
        ),
    ]


class Type3(str, Enum):
    audio_features = "audio_features"


class AudioFeaturesObject(BaseModel):
    acousticness: Annotated[
        float | None,
        Field(
            description="A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic.\n",
            examples=[0.00242],
            ge=0.0,
            le=1.0,
        ),
    ] = None
    analysis_url: Annotated[
        str | None,
        Field(
            description="A URL to access the full audio analysis of this track. An access token is required to access this data.\n",
            examples=[
                "https://api.spotify.com/v1/audio-analysis/2takcwOaAZWiXQijPHIx7B\n"
            ],
        ),
    ] = None
    danceability: Annotated[
        float | None,
        Field(
            description="Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.\n",
            examples=[0.585],
        ),
    ] = None
    duration_ms: Annotated[
        int | None,
        Field(
            description="The duration of the track in milliseconds.\n",
            examples=[237040],
        ),
    ] = None
    energy: Annotated[
        float | None,
        Field(
            description="Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.\n",
            examples=[0.842],
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The Spotify ID for the track.\n",
            examples=["2takcwOaAZWiXQijPHIx7B"],
        ),
    ] = None
    instrumentalness: Annotated[
        float | None,
        Field(
            description='Predicts whether a track contains no vocals. "Ooh" and "aah" sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly "vocal". The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is higher as the value approaches 1.0.\n',
            examples=[0.00686],
        ),
    ] = None
    key: Key | None = None
    liveness: Annotated[
        float | None,
        Field(
            description="Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live.\n",
            examples=[0.0866],
        ),
    ] = None
    loudness: Loudness | None = None
    mode: Mode | None = None
    speechiness: Annotated[
        float | None,
        Field(
            description="Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks.\n",
            examples=[0.0556],
        ),
    ] = None
    tempo: Tempo | None = None
    time_signature: TimeSignature | None = None
    track_href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint providing full details of the track.\n",
            examples=["https://api.spotify.com/v1/tracks/2takcwOaAZWiXQijPHIx7B\n"],
        ),
    ] = None
    type: Annotated[Type3 | None, Field(description="The object type.\n")] = None
    uri: Annotated[
        str | None,
        Field(
            description="The Spotify URI for the track.\n",
            examples=["spotify:track:2takcwOaAZWiXQijPHIx7B"],
        ),
    ] = None
    valence: Annotated[
        float | None,
        Field(
            description="A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).\n",
            examples=[0.428],
            ge=0.0,
            le=1.0,
        ),
    ] = None


class DeviceObject(BaseModel):
    id: Annotated[
        str | None,
        Field(
            description="The device ID. This ID is unique and persistent to some extent. However, this is not guaranteed and any cached `device_id` should periodically be cleared out and refetched as necessary."
        ),
    ] = None
    is_active: Annotated[
        bool | None, Field(description="If this device is the currently active device.")
    ] = None
    is_private_session: Annotated[
        bool | None,
        Field(description="If this device is currently in a private session."),
    ] = None
    is_restricted: Annotated[
        bool | None,
        Field(
            description='Whether controlling this device is restricted. At present if this is "true" then no Web API commands will be accepted by this device.'
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(
            description='A human-readable name for the device. Some devices have a name that the user can configure (e.g. \\"Loudest speaker\\") and some devices have a generic name associated with the manufacturer or device model.',
            examples=["Kitchen speaker"],
        ),
    ] = None
    type: Annotated[
        str | None,
        Field(
            description='Device type, such as "computer", "smartphone" or "speaker".',
            examples=["computer"],
        ),
    ] = None
    volume_percent: Annotated[
        int | None,
        Field(
            description="The current volume in percent.", examples=[59], ge=0, le=100
        ),
    ] = None
    supports_volume: Annotated[
        bool | None, Field(description="If this device can be used to set the volume.")
    ] = None


class CursorObject(BaseModel):
    after: Annotated[
        str | None,
        Field(description="The cursor to use as key to find the next page of items."),
    ] = None
    before: Annotated[
        str | None,
        Field(
            description="The cursor to use as key to find the previous page of items."
        ),
    ] = None


class CursorPagingObject(BaseModel):
    href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint returning the full result of the request."
        ),
    ] = None
    limit: Annotated[
        int | None,
        Field(
            description="The maximum number of items in the response (as set in the query or by default)."
        ),
    ] = None
    next: Annotated[
        str | None,
        Field(description="URL to the next page of items. ( `null` if none)"),
    ] = None
    cursors: Annotated[
        CursorObject | None,
        Field(description="The cursors used to find the next set of items."),
    ] = None
    total: Annotated[
        int | None, Field(description="The total number of items available to return.")
    ] = None


class PagingObject(BaseModel):
    href: Annotated[
        str,
        Field(
            description="A link to the Web API endpoint returning the full result of the request\n",
            examples=["https://api.spotify.com/v1/me/shows?offset=0&limit=20\n"],
        ),
    ]
    limit: Annotated[
        int,
        Field(
            description="The maximum number of items in the response (as set in the query or by default).\n",
            examples=[20],
        ),
    ]
    next: Annotated[
        str,
        Field(
            description="URL to the next page of items. ( `null` if none)\n",
            examples=["https://api.spotify.com/v1/me/shows?offset=1&limit=1"],
        ),
    ]
    offset: Annotated[
        int,
        Field(
            description="The offset of the items returned (as set in the query or by default)\n",
            examples=[0],
        ),
    ]
    previous: Annotated[
        str,
        Field(
            description="URL to the previous page of items. ( `null` if none)\n",
            examples=["https://api.spotify.com/v1/me/shows?offset=1&limit=1"],
        ),
    ]
    total: Annotated[
        int,
        Field(
            description="The total number of items available to return.\n", examples=[4]
        ),
    ]


class RecommendationSeedObject(BaseModel):
    afterFilteringSize: Annotated[
        int | None,
        Field(
            description="The number of tracks available after min\\_\\* and max\\_\\* filters have been applied.\n"
        ),
    ] = None
    afterRelinkingSize: Annotated[
        int | None,
        Field(
            description="The number of tracks available after relinking for regional availability.\n"
        ),
    ] = None
    href: Annotated[
        str | None,
        Field(
            description="A link to the full track or artist data for this seed. For tracks this will be a link to a Track Object. For artists a link to an Artist Object. For genre seeds, this value will be `null`.\n"
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The id used to select this seed. This will be the same as the string used in the `seed_artists`, `seed_tracks` or `seed_genres` parameter.\n"
        ),
    ] = None
    initialPoolSize: Annotated[
        int | None,
        Field(
            description="The number of recommended tracks available for this seed.\n"
        ),
    ] = None
    type: Annotated[
        str | None,
        Field(
            description="The entity type of this seed. One of `artist`, `track` or `genre`.\n"
        ),
    ] = None


class PlaylistTracksRefObject(BaseModel):
    href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint where full details of the playlist's tracks can be retrieved.\n"
        ),
    ] = None
    total: Annotated[
        int | None, Field(description="Number of tracks in the playlist.\n")
    ] = None


class Type4(str, Enum):
    user = "user"


class Type5(str, Enum):
    track = "track"


class ReleaseDatePrecision(str, Enum):
    year = "year"
    month = "month"
    day = "day"


class Type6(str, Enum):
    episode = "episode"


class ResumePointObject(BaseModel):
    fully_played: Annotated[
        bool | None,
        Field(
            description="Whether or not the episode has been fully played by the user.\n"
        ),
    ] = None
    resume_position_ms: Annotated[
        int | None,
        Field(
            description="The user's most recent position in the episode in milliseconds.\n"
        ),
    ] = None


class Type7(str, Enum):
    show = "show"


class Type8(str, Enum):
    audiobook = "audiobook"


class AlbumType(str, Enum):
    album = "album"
    single = "single"
    compilation = "compilation"


class Type9(str, Enum):
    album = "album"


class AlbumGroup(str, Enum):
    album = "album"
    single = "single"
    compilation = "compilation"
    appears_on = "appears_on"


class Type10(str, Enum):
    episode = "episode"


class CopyrightObject(BaseModel):
    text: Annotated[
        str | None, Field(description="The copyright text for this content.\n")
    ] = None
    type: Annotated[
        str | None,
        Field(
            description="The type of copyright: `C` = the copyright, `P` = the sound recording (performance) copyright.\n"
        ),
    ] = None


class AuthorObject(BaseModel):
    name: Annotated[str | None, Field(description="The name of the author.\n")] = None


class NarratorObject(BaseModel):
    name: Annotated[str | None, Field(description="The name of the Narrator.\n")] = None


class ExternalIdObject(BaseModel):
    isrc: Annotated[
        str | None,
        Field(
            description="[International Standard Recording Code](http://en.wikipedia.org/wiki/International_Standard_Recording_Code)\n"
        ),
    ] = None
    ean: Annotated[
        str | None,
        Field(
            description="[International Article Number](http://en.wikipedia.org/wiki/International_Article_Number_%28EAN%29)\n"
        ),
    ] = None
    upc: Annotated[
        str | None,
        Field(
            description="[Universal Product Code](http://en.wikipedia.org/wiki/Universal_Product_Code)\n"
        ),
    ] = None


class ExternalUrlObject(BaseModel):
    spotify: Annotated[
        str | None,
        Field(
            description="The [Spotify URL](/documentation/web-api/concepts/spotify-uris-ids) for the object.\n"
        ),
    ] = None


class FollowersObject(BaseModel):
    href: Annotated[
        str | None,
        Field(
            description="This will always be set to null, as the Web API does not support it at the moment.\n"
        ),
    ] = None
    total: Annotated[
        int | None, Field(description="The total number of followers.\n")
    ] = None


class ImageObject(BaseModel):
    url: Annotated[
        str,
        Field(
            description="The source URL of the image.\n",
            examples=[
                "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228\n"
            ],
        ),
    ]
    height: Annotated[
        int, Field(description="The image height in pixels.\n", examples=[300])
    ]
    width: Annotated[
        int, Field(description="The image width in pixels.\n", examples=[300])
    ]


class ExplicitContentSettingsObject(BaseModel):
    filter_enabled: Annotated[
        bool | None,
        Field(
            description="When `true`, indicates that explicit content should not be played.\n"
        ),
    ] = None
    filter_locked: Annotated[
        bool | None,
        Field(
            description="When `true`, indicates that the explicit content setting is locked and can't be changed by the user.\n"
        ),
    ] = None


class LinkedTrackObject(BaseModel):
    external_urls: Annotated[
        ExternalUrlObject | None,
        Field(description="Known external URLs for this track.\n"),
    ] = None
    href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint providing full details of the track.\n"
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the track.\n"
        ),
    ] = None
    type: Annotated[str | None, Field(description='The object type: "track".\n')] = None
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the track.\n"
        ),
    ] = None


class ArtistObject(BaseModel):
    external_urls: Annotated[
        ExternalUrlObject | None,
        Field(description="Known external URLs for this artist.\n"),
    ] = None
    followers: Annotated[
        FollowersObject | None,
        Field(
            deprecated=True,
            description="Information about the followers of the artist.\n",
        ),
    ] = None
    genres: Annotated[
        list[str] | None,
        Field(
            deprecated=True,
            description="A list of the genres the artist is associated with. If not yet classified, the array is empty.\n",
            examples=[["Prog rock", "Grunge"]],
        ),
    ] = None
    href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint providing full details of the artist.\n"
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the artist.\n"
        ),
    ] = None
    images: Annotated[
        list[ImageObject] | None,
        Field(description="Images of the artist in various sizes, widest first.\n"),
    ] = None
    name: Annotated[str | None, Field(description="The name of the artist.\n")] = None
    popularity: Annotated[
        int | None,
        Field(
            deprecated=True,
            description="The popularity of the artist. The value will be between 0 and 100, with 100 being the most popular. The artist's popularity is calculated from the popularity of all the artist's tracks.\n",
        ),
    ] = None
    type: Annotated[Type | None, Field(description="The object type.\n")] = None
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the artist.\n"
        ),
    ] = None


class SimplifiedArtistObject(BaseModel):
    external_urls: Annotated[
        ExternalUrlObject | None,
        Field(description="Known external URLs for this artist.\n"),
    ] = None
    href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint providing full details of the artist.\n"
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the artist.\n"
        ),
    ] = None
    name: Annotated[str | None, Field(description="The name of the artist.\n")] = None
    type: Annotated[Type | None, Field(description="The object type.\n")] = None
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the artist.\n"
        ),
    ] = None


class PrivateUserObject(BaseModel):
    account_id: Annotated[
        str | None,
        Field(
            description="A public, immutable, pseudoanonymous identifier for the user's account. Use this field for account linking rather than the `id` field, as it is stable and will not change over the lifetime of the account.\n",
            examples=["aB3dE5fG7h"],
        ),
    ] = None
    country: Annotated[
        str | None,
        Field(
            deprecated=True,
            description="The country of the user, as set in the user's account profile. An [ISO 3166-1 alpha-2 country code](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). _This field is only available when the current user has granted access to the [user-read-private](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._\n",
        ),
    ] = None
    display_name: Annotated[
        str | None,
        Field(
            description="The name displayed on the user's profile. `null` if not available.\n"
        ),
    ] = None
    email: Annotated[
        str | None,
        Field(
            deprecated=True,
            description="The user's email address, as entered by the user when creating their account. _**Important!** This email address is unverified; there is no proof that it actually belongs to the user._ _This field is only available when the current user has granted access to the [user-read-email](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._\n",
        ),
    ] = None
    explicit_content: Annotated[
        ExplicitContentSettingsObject | None,
        Field(
            deprecated=True,
            description="The user's explicit content settings. _This field is only available when the current user has granted access to the [user-read-private](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._\n",
        ),
    ] = None
    external_urls: Annotated[
        ExternalUrlObject | None,
        Field(description="Known external URLs for this user."),
    ] = None
    followers: Annotated[
        FollowersObject | None,
        Field(
            deprecated=True, description="Information about the followers of the user."
        ),
    ] = None
    href: Annotated[
        str | None, Field(description="A link to the Web API endpoint for this user.\n")
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The [Spotify user ID](/documentation/web-api/concepts/spotify-uris-ids) for the user. Do not use this field for account linking — use `account_id` instead, which is immutable.\n"
        ),
    ] = None
    images: Annotated[
        list[ImageObject] | None, Field(description="The user's profile image.")
    ] = None
    product: Annotated[
        str | None,
        Field(
            deprecated=True,
            description='The user\'s Spotify subscription level: "premium", "free", etc. (The subscription level "open" can be considered the same as "free".) _This field is only available when the current user has granted access to the [user-read-private](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._\n',
        ),
    ] = None
    type: Annotated[str | None, Field(description='The object type: "user"\n')] = None
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the user.\n"
        ),
    ] = None


class PublicUserObject(BaseModel):
    display_name: Annotated[
        str | None,
        Field(
            description="The name displayed on the user's profile. `null` if not available.\n"
        ),
    ] = None
    external_urls: Annotated[
        ExternalUrlObject | None,
        Field(description="Known public external URLs for this user.\n"),
    ] = None
    followers: Annotated[
        FollowersObject | None,
        Field(
            deprecated=True,
            description="Information about the followers of this user.\n",
        ),
    ] = None
    href: Annotated[
        str | None, Field(description="A link to the Web API endpoint for this user.\n")
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The [Spotify user ID](/documentation/web-api/concepts/spotify-uris-ids) for this user.\n"
        ),
    ] = None
    images: Annotated[
        list[ImageObject] | None, Field(description="The user's profile image.\n")
    ] = None
    type: Annotated[Type2 | None, Field(description="The object type.\n")] = None
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for this user.\n"
        ),
    ] = None


class Track(BaseModel):
    num_samples: Annotated[
        int | None,
        Field(
            description="The exact number of audio samples analyzed from this track. See also `analysis_sample_rate`.",
            examples=[4585515],
        ),
    ] = None
    duration: Annotated[
        float | None,
        Field(description="Length of the track in seconds.", examples=[207.95985]),
    ] = None
    sample_md5: Annotated[
        str | None,
        Field(description="This field will always contain the empty string."),
    ] = None
    offset_seconds: Annotated[
        int | None,
        Field(
            description="An offset to the start of the region of the track that was analyzed. (As the entire track is analyzed, this should always be 0.)",
            examples=[0],
        ),
    ] = None
    window_seconds: Annotated[
        int | None,
        Field(
            description="The length of the region of the track was analyzed, if a subset of the track was analyzed. (As the entire track is analyzed, this should always be 0.)",
            examples=[0],
        ),
    ] = None
    analysis_sample_rate: Annotated[
        int | None,
        Field(
            description="The sample rate used to decode and analyze this track. May differ from the actual sample rate of this track available on Spotify.",
            examples=[22050],
        ),
    ] = None
    analysis_channels: Annotated[
        int | None,
        Field(
            description="The number of channels used for analysis. If 1, all channels are summed together to mono before analysis.",
            examples=[1],
        ),
    ] = None
    end_of_fade_in: Annotated[
        float | None,
        Field(
            description="The time, in seconds, at which the track's fade-in period ends. If the track has no fade-in, this will be 0.0.",
            examples=[0.0],
        ),
    ] = None
    start_of_fade_out: Annotated[
        float | None,
        Field(
            description="The time, in seconds, at which the track's fade-out period starts. If the track has no fade-out, this should match the track's length.",
            examples=[201.13705],
        ),
    ] = None
    loudness: Loudness | None = None
    tempo: Tempo | None = None
    tempo_confidence: Annotated[
        float | None,
        Field(
            description="The confidence, from 0.0 to 1.0, of the reliability of the `tempo`.",
            examples=[0.73],
            ge=0.0,
            le=1.0,
        ),
    ] = None
    time_signature: TimeSignature | None = None
    time_signature_confidence: Annotated[
        float | None,
        Field(
            description="The confidence, from 0.0 to 1.0, of the reliability of the `time_signature`.",
            examples=[0.994],
            ge=0.0,
            le=1.0,
        ),
    ] = None
    key: Key | None = None
    key_confidence: Annotated[
        float | None,
        Field(
            description="The confidence, from 0.0 to 1.0, of the reliability of the `key`.",
            examples=[0.408],
            ge=0.0,
            le=1.0,
        ),
    ] = None
    mode: Mode | None = None
    mode_confidence: Annotated[
        float | None,
        Field(
            description="The confidence, from 0.0 to 1.0, of the reliability of the `mode`.",
            examples=[0.485],
            ge=0.0,
            le=1.0,
        ),
    ] = None
    codestring: Annotated[
        str | None,
        Field(
            description="An [Echo Nest Musical Fingerprint (ENMFP)](https://academiccommons.columbia.edu/doi/10.7916/D8Q248M4) codestring for this track."
        ),
    ] = None
    code_version: Annotated[
        float | None,
        Field(
            description="A version number for the Echo Nest Musical Fingerprint format used in the codestring field.",
            examples=[3.15],
        ),
    ] = None
    echoprintstring: Annotated[
        str | None,
        Field(
            description="An [EchoPrint](https://github.com/spotify/echoprint-codegen) codestring for this track."
        ),
    ] = None
    echoprint_version: Annotated[
        float | None,
        Field(
            description="A version number for the EchoPrint format used in the echoprintstring field.",
            examples=[4.15],
        ),
    ] = None
    synchstring: Annotated[
        str | None,
        Field(
            description="A [Synchstring](https://github.com/echonest/synchdata) for this track."
        ),
    ] = None
    synch_version: Annotated[
        float | None,
        Field(
            description="A version number for the Synchstring used in the synchstring field.",
            examples=[1.0],
        ),
    ] = None
    rhythmstring: Annotated[
        str | None,
        Field(
            description="A Rhythmstring for this track. The format of this string is similar to the Synchstring."
        ),
    ] = None
    rhythm_version: Annotated[
        float | None,
        Field(
            description="A version number for the Rhythmstring used in the rhythmstring field.",
            examples=[1.0],
        ),
    ] = None


class SectionObject(BaseModel):
    start: Annotated[
        float | None,
        Field(
            description="The starting point (in seconds) of the section.",
            examples=[0.0],
        ),
    ] = None
    duration: Annotated[
        float | None,
        Field(
            description="The duration (in seconds) of the section.", examples=[6.97092]
        ),
    ] = None
    confidence: Annotated[
        float | None,
        Field(
            description='The confidence, from 0.0 to 1.0, of the reliability of the section\'s "designation".',
            examples=[1.0],
            ge=0.0,
            le=1.0,
        ),
    ] = None
    loudness: Annotated[
        float | None,
        Field(
            description="The overall loudness of the section in decibels (dB). Loudness values are useful for comparing relative loudness of sections within tracks.",
            examples=[-14.938],
        ),
    ] = None
    tempo: Annotated[
        float | None,
        Field(
            description="The overall estimated tempo of the section in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.",
            examples=[113.178],
        ),
    ] = None
    tempo_confidence: Annotated[
        float | None,
        Field(
            description="The confidence, from 0.0 to 1.0, of the reliability of the tempo. Some tracks contain tempo changes or sounds which don't contain tempo (like pure speech) which would correspond to a low value in this field.",
            examples=[0.647],
            ge=0.0,
            le=1.0,
        ),
    ] = None
    key: Annotated[
        int | None,
        Field(
            description="The estimated overall key of the section. The values in this field ranging from 0 to 11 mapping to pitches using standard Pitch Class notation (E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on). If no key was detected, the value is -1.",
            examples=[9],
        ),
    ] = None
    key_confidence: Annotated[
        float | None,
        Field(
            description="The confidence, from 0.0 to 1.0, of the reliability of the key. Songs with many key changes may correspond to low values in this field.",
            examples=[0.297],
            ge=0.0,
            le=1.0,
        ),
    ] = None
    mode: Annotated[
        Mode1 | None,
        Field(
            description='Indicates the modality (major or minor) of a section, the type of scale from which its melodic content is derived. This field will contain a 0 for "minor", a 1 for "major", or a -1 for no result. Note that the major key (e.g. C major) could more likely be confused with the minor key at 3 semitones lower (e.g. A minor) as both keys carry the same pitches.'
        ),
    ] = None
    mode_confidence: Annotated[
        float | None,
        Field(
            description="The confidence, from 0.0 to 1.0, of the reliability of the `mode`.",
            examples=[0.471],
            ge=0.0,
            le=1.0,
        ),
    ] = None
    time_signature: TimeSignature | None = None
    time_signature_confidence: Annotated[
        float | None,
        Field(
            description="The confidence, from 0.0 to 1.0, of the reliability of the `time_signature`. Sections with time signature changes may correspond to low values in this field.",
            examples=[1.0],
            ge=0.0,
            le=1.0,
        ),
    ] = None


class SimplifiedTrackObject(BaseModel):
    artists: Annotated[
        list[SimplifiedArtistObject] | None,
        Field(
            description="The artists who performed the track. Each artist object includes a link in `href` to more detailed information about the artist."
        ),
    ] = None
    available_markets: Annotated[
        list[str] | None,
        Field(
            deprecated=True,
            description="A list of the countries in which the track can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code.\n",
        ),
    ] = None
    disc_number: Annotated[
        int | None,
        Field(
            description="The disc number (usually `1` unless the album consists of more than one disc)."
        ),
    ] = None
    duration_ms: Annotated[
        int | None, Field(description="The track length in milliseconds.")
    ] = None
    explicit: Annotated[
        bool | None,
        Field(
            description="Whether or not the track has explicit lyrics ( `true` = yes it does; `false` = no it does not OR unknown)."
        ),
    ] = None
    external_urls: Annotated[
        ExternalUrlObject | None, Field(description="External URLs for this track.\n")
    ] = None
    href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint providing full details of the track."
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the track.\n"
        ),
    ] = None
    is_playable: Annotated[
        bool | None,
        Field(
            description="Part of the response when [Track Relinking](/documentation/web-api/concepts/track-relinking/) is applied. If `true`, the track is playable in the given market. Otherwise `false`.\n"
        ),
    ] = None
    linked_from: Annotated[
        LinkedTrackObject | None,
        Field(
            deprecated=True,
            description="Part of the response when [Track Relinking](/documentation/web-api/concepts/track-relinking/) is applied and is only part of the response if the track linking, in fact, exists. The requested track has been replaced with a different track. The track in the `linked_from` object contains information about the originally requested track.",
        ),
    ] = None
    restrictions: Annotated[
        TrackRestrictionObject | None,
        Field(
            description="Included in the response when a content restriction is applied.\n"
        ),
    ] = None
    name: Annotated[str | None, Field(description="The name of the track.")] = None
    preview_url: Annotated[
        str | None,
        Field(
            deprecated=True,
            description="A URL to a 30 second preview (MP3 format) of the track.\n",
        ),
    ] = None
    track_number: Annotated[
        int | None,
        Field(
            description="The number of the track. If an album has several discs, the track number is the number on the specified disc.\n"
        ),
    ] = None
    type: Annotated[str | None, Field(description='The object type: "track".\n')] = None
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the track.\n"
        ),
    ] = None
    is_local: Annotated[
        bool | None,
        Field(description="Whether or not the track is from a local file.\n"),
    ] = None


class CursorPagingSimplifiedArtistObject(CursorPagingObject):
    items: list[ArtistObject] | None = None


class PagingSimplifiedTrackObject(PagingObject):
    items: list[SimplifiedTrackObject] | None = None


class PagingArtistObject(PagingObject):
    items: list[ArtistObject] | None = None


class PlaylistUserObject(BaseModel):
    external_urls: Annotated[
        ExternalUrlObject | None,
        Field(description="Known public external URLs for this user.\n"),
    ] = None
    href: Annotated[
        str | None, Field(description="A link to the Web API endpoint for this user.\n")
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The [Spotify user ID](/documentation/web-api/concepts/spotify-uris-ids) for this user.\n"
        ),
    ] = None
    type: Annotated[Type4 | None, Field(description="The object type.\n")] = None
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for this user.\n"
        ),
    ] = None


class PlaylistOwnerObject(PlaylistUserObject):
    display_name: Annotated[
        str | None,
        Field(
            description="The name displayed on the user's profile. `null` if not available.\n"
        ),
    ] = None


class CategoryObject(BaseModel):
    href: Annotated[
        str,
        Field(
            description="A link to the Web API endpoint returning full details of the category.\n"
        ),
    ]
    icons: Annotated[
        list[ImageObject], Field(description="The category icon, in various sizes.\n")
    ]
    id: Annotated[
        str,
        Field(
            description="The [Spotify category ID](/documentation/web-api/concepts/spotify-uris-ids) of the category.\n",
            examples=["equal"],
        ),
    ]
    name: Annotated[
        str, Field(description="The name of the category.\n", examples=["EQUAL"])
    ]


class EpisodeBase(BaseModel):
    audio_preview_url: Annotated[
        str,
        Field(
            deprecated=True,
            description="A URL to a 30 second preview (MP3 format) of the episode. `null` if not available.\n",
            examples=[
                "https://p.scdn.co/mp3-preview/2f37da1d4221f40b9d1a98cd191f4d6f1646ad17"
            ],
        ),
    ]
    description: Annotated[
        str,
        Field(
            description="A description of the episode. HTML tags are stripped away from this field, use `html_description` field in case HTML tags are needed.\n",
            examples=[
                "A Spotify podcast sharing fresh insights on important topics of the moment—in a way only Spotify can. You’ll hear from experts in the music, podcast and tech industries as we discover and uncover stories about our work and the world around us.\n"
            ],
        ),
    ]
    html_description: Annotated[
        str,
        Field(
            description="A description of the episode. This field may contain HTML tags.\n",
            examples=[
                "<p>A Spotify podcast sharing fresh insights on important topics of the moment—in a way only Spotify can. You’ll hear from experts in the music, podcast and tech industries as we discover and uncover stories about our work and the world around us.</p>\n"
            ],
        ),
    ]
    duration_ms: Annotated[
        int,
        Field(description="The episode length in milliseconds.\n", examples=[1686230]),
    ]
    explicit: Annotated[
        bool,
        Field(
            description="Whether or not the episode has explicit content (true = yes it does; false = no it does not OR unknown).\n"
        ),
    ]
    external_urls: Annotated[
        ExternalUrlObject, Field(description="External URLs for this episode.\n")
    ]
    href: Annotated[
        str,
        Field(
            description="A link to the Web API endpoint providing full details of the episode.\n",
            examples=["https://api.spotify.com/v1/episodes/5Xt5DXGzch68nYYamXrNxZ"],
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the episode.\n",
            examples=["5Xt5DXGzch68nYYamXrNxZ"],
        ),
    ]
    images: Annotated[
        list[ImageObject],
        Field(
            description="The cover art for the episode in various sizes, widest first.\n"
        ),
    ]
    is_externally_hosted: Annotated[
        bool,
        Field(description="True if the episode is hosted outside of Spotify's CDN.\n"),
    ]
    is_playable: Annotated[
        bool,
        Field(
            description="True if the episode is playable in the given market. Otherwise false.\n"
        ),
    ]
    language: Annotated[
        str | None,
        Field(
            deprecated=True,
            description="The language used in the episode, identified by a [ISO 639](https://en.wikipedia.org/wiki/ISO_639) code. This field is deprecated and might be removed in the future. Please use the `languages` field instead.\n",
            examples=["en"],
        ),
    ] = None
    languages: Annotated[
        list[str],
        Field(
            description="A list of the languages used in the episode, identified by their [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639) code.\n",
            examples=[["fr", "en"]],
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="The name of the episode.\n",
            examples=[
                "Starting Your Own Podcast: Tips, Tricks, and Advice From Anchor Creators\n"
            ],
        ),
    ]
    release_date: Annotated[
        str,
        Field(
            description='The date the episode was first released, for example `"1981-12-15"`. Depending on the precision, it might be shown as `"1981"` or `"1981-12"`.\n',
            examples=["1981-12-15"],
        ),
    ]
    release_date_precision: Annotated[
        ReleaseDatePrecision,
        Field(
            description="The precision with which `release_date` value is known.\n",
            examples=["day"],
        ),
    ]
    resume_point: Annotated[
        ResumePointObject | None,
        Field(
            description="The user's most recent position in the episode. Set if the supplied access token is a user token and has the scope 'user-read-playback-position'.\n"
        ),
    ] = None
    type: Annotated[Type6, Field(description="The object type.\n")]
    uri: Annotated[
        str,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the episode.\n",
            examples=["spotify:episode:0zLhl3WsOCQHbe1BPTiHgr"],
        ),
    ]
    restrictions: Annotated[
        EpisodeRestrictionObject | None,
        Field(
            description="Included in the response when a content restriction is applied.\n"
        ),
    ] = None


class ShowBase(BaseModel):
    available_markets: Annotated[
        list[str],
        Field(
            deprecated=True,
            description="A list of the countries in which the show can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code.\n",
        ),
    ]
    copyrights: Annotated[
        list[CopyrightObject],
        Field(description="The copyright statements of the show.\n"),
    ]
    description: Annotated[
        str,
        Field(
            description="A description of the show. HTML tags are stripped away from this field, use `html_description` field in case HTML tags are needed.\n"
        ),
    ]
    html_description: Annotated[
        str,
        Field(
            description="A description of the show. This field may contain HTML tags.\n"
        ),
    ]
    explicit: Annotated[
        bool,
        Field(
            description="Whether or not the show has explicit content (true = yes it does; false = no it does not OR unknown).\n"
        ),
    ]
    external_urls: Annotated[
        ExternalUrlObject, Field(description="External URLs for this show.\n")
    ]
    href: Annotated[
        str,
        Field(
            description="A link to the Web API endpoint providing full details of the show.\n"
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the show.\n"
        ),
    ]
    images: Annotated[
        list[ImageObject],
        Field(
            description="The cover art for the show in various sizes, widest first.\n"
        ),
    ]
    is_externally_hosted: Annotated[
        bool,
        Field(
            description="True if all of the shows episodes are hosted outside of Spotify's CDN. This field might be `null` in some cases.\n"
        ),
    ]
    languages: Annotated[
        list[str],
        Field(
            description="A list of the languages used in the show, identified by their [ISO 639](https://en.wikipedia.org/wiki/ISO_639) code.\n"
        ),
    ]
    media_type: Annotated[str, Field(description="The media type of the show.\n")]
    name: Annotated[str, Field(description="The name of the episode.\n")]
    publisher: Annotated[
        str, Field(deprecated=True, description="The publisher of the show.\n")
    ]
    type: Annotated[Type7, Field(description="The object type.\n")]
    uri: Annotated[
        str,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the show.\n"
        ),
    ]
    total_episodes: Annotated[
        int, Field(description="The total number of episodes in the show.\n")
    ]


class SimplifiedShowObject(ShowBase):
    pass


class AudiobookBase(BaseModel):
    authors: Annotated[
        list[AuthorObject], Field(description="The author(s) for the audiobook.\n")
    ]
    available_markets: Annotated[
        list[str],
        Field(
            deprecated=True,
            description="A list of the countries in which the audiobook can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code.\n",
        ),
    ]
    copyrights: Annotated[
        list[CopyrightObject],
        Field(description="The copyright statements of the audiobook.\n"),
    ]
    description: Annotated[
        str,
        Field(
            description="A description of the audiobook. HTML tags are stripped away from this field, use `html_description` field in case HTML tags are needed.\n"
        ),
    ]
    html_description: Annotated[
        str,
        Field(
            description="A description of the audiobook. This field may contain HTML tags.\n"
        ),
    ]
    edition: Annotated[
        str | None,
        Field(description="The edition of the audiobook.\n", examples=["Unabridged"]),
    ] = None
    explicit: Annotated[
        bool,
        Field(
            description="Whether or not the audiobook has explicit content (true = yes it does; false = no it does not OR unknown).\n"
        ),
    ]
    external_urls: Annotated[
        ExternalUrlObject, Field(description="External URLs for this audiobook.\n")
    ]
    href: Annotated[
        str,
        Field(
            description="A link to the Web API endpoint providing full details of the audiobook.\n"
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the audiobook.\n"
        ),
    ]
    images: Annotated[
        list[ImageObject],
        Field(
            description="The cover art for the audiobook in various sizes, widest first.\n"
        ),
    ]
    languages: Annotated[
        list[str],
        Field(
            description="A list of the languages used in the audiobook, identified by their [ISO 639](https://en.wikipedia.org/wiki/ISO_639) code.\n"
        ),
    ]
    media_type: Annotated[str, Field(description="The media type of the audiobook.\n")]
    name: Annotated[str, Field(description="The name of the audiobook.\n")]
    narrators: Annotated[
        list[NarratorObject], Field(description="The narrator(s) for the audiobook.\n")
    ]
    publisher: Annotated[
        str, Field(deprecated=True, description="The publisher of the audiobook.\n")
    ]
    type: Annotated[Type8, Field(description="The object type.\n")]
    uri: Annotated[
        str,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the audiobook.\n"
        ),
    ]
    total_chapters: Annotated[
        int, Field(description="The number of chapters in this audiobook.\n")
    ]


class SimplifiedAudiobookObject(AudiobookBase):
    pass


class AlbumBase(BaseModel):
    album_type: Annotated[
        AlbumType,
        Field(description="The type of the album.\n", examples=["compilation"]),
    ]
    total_tracks: Annotated[
        int, Field(description="The number of tracks in the album.", examples=[9])
    ]
    available_markets: Annotated[
        list[str],
        Field(
            deprecated=True,
            description="The markets in which the album is available: [ISO 3166-1 alpha-2 country codes](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). _**NOTE**: an album is considered available in a market when at least 1 of its tracks is available in that market._\n",
            examples=[["CA", "BR", "IT"]],
        ),
    ]
    external_urls: Annotated[
        ExternalUrlObject, Field(description="Known external URLs for this album.\n")
    ]
    href: Annotated[
        str,
        Field(
            description="A link to the Web API endpoint providing full details of the album.\n"
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the album.\n",
            examples=["2up3OPMp9Tb4dAKM2erWXQ"],
        ),
    ]
    images: Annotated[
        list[ImageObject],
        Field(
            description="The cover art for the album in various sizes, widest first.\n"
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="The name of the album. In case of an album takedown, the value may be an empty string.\n"
        ),
    ]
    release_date: Annotated[
        str,
        Field(
            description="The date the album was first released.\n", examples=["1981-12"]
        ),
    ]
    release_date_precision: Annotated[
        ReleaseDatePrecision,
        Field(
            description="The precision with which `release_date` value is known.\n",
            examples=["year"],
        ),
    ]
    restrictions: Annotated[
        AlbumRestrictionObject | None,
        Field(
            description="Included in the response when a content restriction is applied.\n"
        ),
    ] = None
    type: Annotated[Type9, Field(description="The object type.\n")]
    uri: Annotated[
        str,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the album.\n",
            examples=["spotify:album:2up3OPMp9Tb4dAKM2erWXQ"],
        ),
    ]


class SimplifiedAlbumObject(AlbumBase):
    artists: Annotated[
        list[SimplifiedArtistObject],
        Field(
            description="The artists of the album. Each artist object includes a link in `href` to more detailed information about the artist.\n"
        ),
    ]


class ArtistDiscographyAlbumObject(SimplifiedAlbumObject):
    album_group: Annotated[
        AlbumGroup,
        Field(
            deprecated=True,
            description="This field describes the relationship between the artist and the album.\n",
            examples=["compilation"],
        ),
    ]


class ChapterBase(BaseModel):
    audio_preview_url: Annotated[
        str,
        Field(
            deprecated=True,
            description="A URL to a 30 second preview (MP3 format) of the chapter. `null` if not available.\n",
            examples=[
                "https://p.scdn.co/mp3-preview/2f37da1d4221f40b9d1a98cd191f4d6f1646ad17"
            ],
        ),
    ]
    available_markets: Annotated[
        list[str] | None,
        Field(
            deprecated=True,
            description="A list of the countries in which the chapter can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code.\n",
        ),
    ] = None
    chapter_number: Annotated[
        int, Field(description="The number of the chapter\n", examples=[1])
    ]
    description: Annotated[
        str,
        Field(
            description="A description of the chapter. HTML tags are stripped away from this field, use `html_description` field in case HTML tags are needed.\n",
            examples=[
                "We kept on ascending, with occasional periods of quick descent, but in the main always ascending. Suddenly, I became conscious of the fact that the driver was in the act of pulling up the horses in the courtyard of a vast ruined castle, from whose tall black windows came no ray of light, and whose broken battlements showed a jagged line against the moonlit sky.\n"
            ],
        ),
    ]
    html_description: Annotated[
        str,
        Field(
            description="A description of the chapter. This field may contain HTML tags.\n",
            examples=[
                "<p>We kept on ascending, with occasional periods of quick descent, but in the main always ascending. Suddenly, I became conscious of the fact that the driver was in the act of pulling up the horses in the courtyard of a vast ruined castle, from whose tall black windows came no ray of light, and whose broken battlements showed a jagged line against the moonlit sky.</p>\n"
            ],
        ),
    ]
    duration_ms: Annotated[
        int,
        Field(description="The chapter length in milliseconds.\n", examples=[1686230]),
    ]
    explicit: Annotated[
        bool,
        Field(
            description="Whether or not the chapter has explicit content (true = yes it does; false = no it does not OR unknown).\n"
        ),
    ]
    external_urls: Annotated[
        ExternalUrlObject, Field(description="External URLs for this chapter.\n")
    ]
    href: Annotated[
        str,
        Field(
            description="A link to the Web API endpoint providing full details of the chapter.\n",
            examples=["https://api.spotify.com/v1/episodes/5Xt5DXGzch68nYYamXrNxZ"],
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the chapter.\n",
            examples=["5Xt5DXGzch68nYYamXrNxZ"],
        ),
    ]
    images: Annotated[
        list[ImageObject],
        Field(
            description="The cover art for the chapter in various sizes, widest first.\n"
        ),
    ]
    is_playable: Annotated[
        bool,
        Field(
            description="True if the chapter is playable in the given market. Otherwise false.\n"
        ),
    ]
    languages: Annotated[
        list[str],
        Field(
            description="A list of the languages used in the chapter, identified by their [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639) code.\n",
            examples=[["fr", "en"]],
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="The name of the chapter.\n",
            examples=[
                "Starting Your Own Podcast: Tips, Tricks, and Advice From Anchor Creators\n"
            ],
        ),
    ]
    release_date: Annotated[
        str,
        Field(
            description='The date the chapter was first released, for example `"1981-12-15"`. Depending on the precision, it might be shown as `"1981"` or `"1981-12"`.\n',
            examples=["1981-12-15"],
        ),
    ]
    release_date_precision: Annotated[
        ReleaseDatePrecision,
        Field(
            description="The precision with which `release_date` value is known.\n",
            examples=["day"],
        ),
    ]
    resume_point: Annotated[
        ResumePointObject | None,
        Field(
            description="The user's most recent position in the chapter. Set if the supplied access token is a user token and has the scope 'user-read-playback-position'.\n"
        ),
    ] = None
    type: Annotated[Type10, Field(description="The object type.\n")]
    uri: Annotated[
        str,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the chapter.\n",
            examples=["spotify:episode:0zLhl3WsOCQHbe1BPTiHgr"],
        ),
    ]
    restrictions: Annotated[
        ChapterRestrictionObject | None,
        Field(
            description="Included in the response when a content restriction is applied.\n"
        ),
    ] = None


class AlbumObject(AlbumBase):
    artists: Annotated[
        list[SimplifiedArtistObject],
        Field(
            description="The artists of the album. Each artist object includes a link in `href` to more detailed information about the artist.\n"
        ),
    ]
    tracks: Annotated[
        PagingSimplifiedTrackObject, Field(description="The tracks of the album.\n")
    ]
    copyrights: Annotated[
        list[CopyrightObject],
        Field(description="The copyright statements of the album.\n"),
    ]
    external_ids: Annotated[
        ExternalIdObject, Field(description="Known external IDs for the album.\n")
    ]
    genres: Annotated[
        list[str],
        Field(
            deprecated=True,
            description="**Deprecated** The array is always empty.\n",
            examples=[[]],
        ),
    ]
    label: Annotated[
        str,
        Field(deprecated=True, description="The label associated with the album.\n"),
    ]
    popularity: Annotated[
        int,
        Field(
            deprecated=True,
            description="The popularity of the album. The value will be between 0 and 100, with 100 being the most popular.\n",
        ),
    ]


class ContextObject(BaseModel):
    type: Annotated[
        str | None,
        Field(
            description='The object type, e.g. "artist", "playlist", "album", "show".\n'
        ),
    ] = None
    href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint providing full details of the track."
        ),
    ] = None
    external_urls: Annotated[
        ExternalUrlObject | None, Field(description="External URLs for this context.")
    ] = None
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the context.\n"
        ),
    ] = None


class AudioAnalysisObject(BaseModel):
    meta: Meta | None = None
    track: Track | None = None
    bars: Annotated[
        list[TimeIntervalObject] | None,
        Field(
            description="The time intervals of the bars throughout the track. A bar (or measure) is a segment of time defined as a given number of beats."
        ),
    ] = None
    beats: Annotated[
        list[TimeIntervalObject] | None,
        Field(
            description="The time intervals of beats throughout the track. A beat is the basic time unit of a piece of music; for example, each tick of a metronome. Beats are typically multiples of tatums."
        ),
    ] = None
    sections: Annotated[
        list[SectionObject] | None,
        Field(
            description="Sections are defined by large variations in rhythm or timbre, e.g. chorus, verse, bridge, guitar solo, etc. Each section contains its own descriptions of tempo, key, mode, time_signature, and loudness."
        ),
    ] = None
    segments: Annotated[
        list[SegmentObject] | None,
        Field(
            description="Each segment contains a roughly conisistent sound throughout its duration."
        ),
    ] = None
    tatums: Annotated[
        list[TimeIntervalObject] | None,
        Field(
            description="A tatum represents the lowest regular pulse train that a listener intuitively infers from the timing of perceived musical events (segments)."
        ),
    ] = None


class PagingArtistDiscographyAlbumObject(PagingObject):
    items: list[ArtistDiscographyAlbumObject] | None = None


class PagingSimplifiedAlbumObject(PagingObject):
    items: list[SimplifiedAlbumObject] | None = None


class PagingSimplifiedShowObject(PagingObject):
    items: list[SimplifiedShowObject] | None = None


class PagingSimplifiedAudiobookObject(PagingObject):
    items: list[SimplifiedAudiobookObject] | None = None


class SavedAlbumObject(BaseModel):
    added_at: Annotated[
        AwareDatetime | None,
        Field(
            description="The date and time the album was saved\nTimestamps are returned in ISO 8601 format as Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ.\nIf the time is imprecise (for example, the date/time of an album release), an additional field indicates the precision; see for example, release_date in an album object.\n"
        ),
    ] = None
    album: Annotated[
        AlbumObject | None, Field(description="Information about the album.")
    ] = None


class SavedShowObject(BaseModel):
    added_at: Annotated[
        AwareDatetime | None,
        Field(
            description="The date and time the show was saved.\nTimestamps are returned in ISO 8601 format as Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ.\nIf the time is imprecise (for example, the date/time of an album release), an additional field indicates the precision; see for example, release_date in an album object.\n"
        ),
    ] = None
    show: Annotated[
        SimplifiedShowObject | None, Field(description="Information about the show.")
    ] = None


class SimplifiedPlaylistObject(BaseModel):
    collaborative: Annotated[
        bool | None,
        Field(
            description="`true` if the owner allows other users to modify the playlist.\n"
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description="The playlist description. _Only returned for modified, verified playlists, otherwise_ `null`.\n"
        ),
    ] = None
    external_urls: Annotated[
        ExternalUrlObject | None,
        Field(description="Known external URLs for this playlist.\n"),
    ] = None
    href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint providing full details of the playlist.\n"
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the playlist.\n"
        ),
    ] = None
    images: Annotated[
        list[ImageObject] | None,
        Field(
            description="Images for the playlist. The array may be empty or contain up to three images. The images are returned by size in descending order. See [Working with Playlists](/documentation/web-api/concepts/playlists). _**Note**: If returned, the source URL for the image (`url`) is temporary and will expire in less than a day._\n"
        ),
    ] = None
    name: Annotated[str | None, Field(description="The name of the playlist.\n")] = None
    owner: Annotated[
        PlaylistOwnerObject | None,
        Field(description="The user who owns the playlist\n"),
    ] = None
    public: Annotated[
        bool | None,
        Field(
            description="The playlist's public/private status (if it is added to the user's profile): `true` the playlist is public, `false` the playlist is private, `null` the playlist status is not relevant. For more about public/private status, see [Working with Playlists](/documentation/web-api/concepts/playlists)\n"
        ),
    ] = None
    snapshot_id: Annotated[
        str | None,
        Field(
            description="The version identifier for the current playlist. Can be supplied in other requests to target a specific playlist version\n"
        ),
    ] = None
    items: Annotated[
        PlaylistTracksRefObject | None,
        Field(
            description="A collection containing a link ( `href` ) to the Web API endpoint where full details of the playlist's items can be retrieved, along with the `total` number of items in the playlist. Note, a track object may be `null`. This can happen if a track is no longer available.\n"
        ),
    ] = None
    tracks: Annotated[
        PlaylistTracksRefObject | None,
        Field(
            deprecated=True,
            description="**Deprecated:** Use `items` instead. A collection containing a link ( `href` ) to the Web API endpoint where full details of the playlist's tracks can be retrieved, along with the `total` number of tracks in the playlist. Note, a track object may be `null`. This can happen if a track is no longer available.\n",
        ),
    ] = None
    type: Annotated[str | None, Field(description='The object type: "playlist"\n')] = (
        None
    )
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the playlist.\n"
        ),
    ] = None


class TrackObject(BaseModel):
    album: Annotated[
        SimplifiedAlbumObject | None,
        Field(
            description="The album on which the track appears. The album object includes a link in `href` to full information about the album.\n"
        ),
    ] = None
    artists: Annotated[
        list[SimplifiedArtistObject] | None,
        Field(
            description="The artists who performed the track. Each artist object includes a link in `href` to more detailed information about the artist.\n"
        ),
    ] = None
    available_markets: Annotated[
        list[str] | None,
        Field(
            deprecated=True,
            description="A list of the countries in which the track can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code.\n",
        ),
    ] = None
    disc_number: Annotated[
        int | None,
        Field(
            description="The disc number (usually `1` unless the album consists of more than one disc).\n"
        ),
    ] = None
    duration_ms: Annotated[
        int | None, Field(description="The track length in milliseconds.\n")
    ] = None
    explicit: Annotated[
        bool | None,
        Field(
            description="Whether or not the track has explicit lyrics ( `true` = yes it does; `false` = no it does not OR unknown).\n"
        ),
    ] = None
    external_ids: Annotated[
        ExternalIdObject | None,
        Field(description="Known external IDs for the track.\n"),
    ] = None
    external_urls: Annotated[
        ExternalUrlObject | None,
        Field(description="Known external URLs for this track.\n"),
    ] = None
    href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint providing full details of the track.\n"
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the track.\n"
        ),
    ] = None
    is_playable: Annotated[
        bool | None,
        Field(
            description="Part of the response when [Track Relinking](/documentation/web-api/concepts/track-relinking) is applied. If `true`, the track is playable in the given market. Otherwise `false`.\n"
        ),
    ] = None
    linked_from: Annotated[
        dict[str, Any] | None,
        Field(
            deprecated=True,
            description="Part of the response when [Track Relinking](/documentation/web-api/concepts/track-relinking) is applied, and the requested track has been replaced with different track. The track in the `linked_from` object contains information about the originally requested track.\n",
        ),
    ] = None
    restrictions: Annotated[
        TrackRestrictionObject | None,
        Field(
            description="Included in the response when a content restriction is applied.\n"
        ),
    ] = None
    name: Annotated[str | None, Field(description="The name of the track.\n")] = None
    popularity: Annotated[
        int | None,
        Field(
            deprecated=True,
            description="The popularity of the track. The value will be between 0 and 100, with 100 being the most popular.<br/>The popularity of a track is a value between 0 and 100, with 100 being the most popular. The popularity is calculated by algorithm and is based, in the most part, on the total number of plays the track has had and how recent those plays are.<br/>Generally speaking, songs that are being played a lot now will have a higher popularity than songs that were played a lot in the past. Duplicate tracks (e.g. the same track from a single and an album) are rated independently. Artist and album popularity is derived mathematically from track popularity. _**Note**: the popularity value may lag actual popularity by a few days: the value is not updated in real time._\n",
        ),
    ] = None
    preview_url: Annotated[
        str | None,
        Field(
            deprecated=True,
            description="A link to a 30 second preview (MP3 format) of the track. Can be `null`\n",
        ),
    ] = None
    track_number: Annotated[
        int | None,
        Field(
            description="The number of the track. If an album has several discs, the track number is the number on the specified disc.\n"
        ),
    ] = None
    type: Annotated[Literal["track"], Field(description='The object type: "track".\n')]
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the track.\n"
        ),
    ] = None
    is_local: Annotated[
        bool | None,
        Field(description="Whether or not the track is from a local file.\n"),
    ] = None


class EpisodeObject(EpisodeBase):
    show: Annotated[
        SimplifiedShowObject,
        Field(description="The show on which the episode belongs.\n"),
    ]
    type: Literal["EpisodeObject"]  # type: ignore[reportIncompatibleVariableOverride]


class SimplifiedEpisodeObject(EpisodeBase):
    pass


class ChapterObject(ChapterBase):
    audiobook: Annotated[
        SimplifiedAudiobookObject,
        Field(description="The audiobook for which the chapter belongs.\n"),
    ]


class SimplifiedChapterObject(ChapterBase):
    pass


class PlayHistoryObject(BaseModel):
    track: Annotated[
        TrackObject | None, Field(description="The track the user listened to.")
    ] = None
    played_at: Annotated[
        AwareDatetime | None,
        Field(description="The date and time the track was played."),
    ] = None
    context: Annotated[
        ContextObject | None,
        Field(description="The context the track was played from."),
    ] = None


class PlaylistTrackObject(BaseModel):
    added_at: Annotated[
        AwareDatetime | None,
        Field(
            description="The date and time the track or episode was added. _**Note**: some very old playlists may return `null` in this field._\n"
        ),
    ] = None
    added_by: Annotated[
        PlaylistUserObject | None,
        Field(
            description="The Spotify user who added the track or episode. _**Note**: some very old playlists may return `null` in this field._\n"
        ),
    ] = None
    is_local: Annotated[
        bool | None,
        Field(
            description="Whether this track or episode is a [local file](/documentation/web-api/concepts/playlists/#local-files) or not.\n"
        ),
    ] = None
    item: Annotated[
        TrackObject | EpisodeObject | None,
        Field(
            description="Information about the track or episode.", discriminator="type"
        ),
    ] = None
    track: Annotated[
        TrackObject | EpisodeObject | None,
        Field(
            deprecated=True,
            description="**Deprecated:** Use `item` instead. Information about the track or episode.\n",
            discriminator="type",
        ),
    ] = None


class Queue(RootModel[TrackObject | EpisodeObject]):
    root: Annotated[TrackObject | EpisodeObject, Field(discriminator="type")]


class QueueObject(BaseModel):
    currently_playing: Annotated[
        TrackObject | EpisodeObject | None,
        Field(
            description="The currently playing track or episode. Can be `null`.",
            discriminator="type",
        ),
    ] = None
    queue: Annotated[
        list[Queue] | None,
        Field(description="The tracks or episodes in the queue. Can be empty."),
    ] = None


class CurrentlyPlayingContextObject(BaseModel):
    device: Annotated[
        DeviceObject | None, Field(description="The device that is currently active.\n")
    ] = None
    repeat_state: Annotated[str | None, Field(description="off, track, context")] = None
    shuffle_state: Annotated[
        bool | None, Field(description="If shuffle is on or off.")
    ] = None
    context: Annotated[
        ContextObject | None, Field(description="A Context Object. Can be `null`.")
    ] = None
    timestamp: Annotated[
        int | None,
        Field(
            description="Unix Millisecond Timestamp when playback state was last changed (play, pause, skip, scrub, new song, etc.)."
        ),
    ] = None
    progress_ms: Annotated[
        int | None,
        Field(
            description="Progress into the currently playing track or episode. Can be `null`."
        ),
    ] = None
    is_playing: Annotated[
        bool | None,
        Field(description="If something is currently playing, return `true`."),
    ] = None
    item: Annotated[
        TrackObject | EpisodeObject | None,
        Field(
            description="The currently playing track or episode. Can be `null`.",
            discriminator="type",
        ),
    ] = None
    currently_playing_type: Annotated[
        str | None,
        Field(
            description="The object type of the currently playing item. Can be one of `track`, `episode`, `ad` or `unknown`.\n"
        ),
    ] = None
    actions: Annotated[
        DisallowsObject | None,
        Field(
            description="Allows to update the user interface based on which playback actions are available within the current context.\n"
        ),
    ] = None


class CursorPagingPlayHistoryObject(CursorPagingObject):
    items: list[PlayHistoryObject] | None = None


class PagingPlaylistObject(PagingObject):
    items: list[SimplifiedPlaylistObject] | None = None


class PagingFeaturedPlaylistObject(BaseModel):
    message: Annotated[
        str | None,
        Field(
            description="The localized message of a playlist.\n",
            examples=["Popular Playlists"],
        ),
    ] = None
    playlists: PagingPlaylistObject | None = None


class PagingSavedAlbumObject(PagingObject):
    items: list[SavedAlbumObject] | None = None


class PagingTrackObject(PagingObject):
    items: list[TrackObject] | None = None


class PagingPlaylistTrackObject(PagingObject):
    items: list[PlaylistTrackObject] | None = None


class PagingSavedShowObject(PagingObject):
    items: list[SavedShowObject] | None = None


class PagingSimplifiedEpisodeObject(PagingObject):
    items: list[SimplifiedEpisodeObject] | None = None


class PagingSimplifiedChapterObject(PagingObject):
    items: list[SimplifiedChapterObject] | None = None


class RecommendationsObject(BaseModel):
    seeds: Annotated[
        list[RecommendationSeedObject],
        Field(description="An array of recommendation seed objects.\n"),
    ]
    tracks: Annotated[
        list[TrackObject],
        Field(
            description="An array of track object (simplified) ordered according to the parameters supplied.\n"
        ),
    ]


class SavedTrackObject(BaseModel):
    added_at: Annotated[
        AwareDatetime | None,
        Field(
            description="The date and time the track was saved.\nTimestamps are returned in ISO 8601 format as Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ.\nIf the time is imprecise (for example, the date/time of an album release), an additional field indicates the precision; see for example, release_date in an album object.\n"
        ),
    ] = None
    track: Annotated[
        TrackObject | None, Field(description="Information about the track.")
    ] = None


class SavedEpisodeObject(BaseModel):
    added_at: Annotated[
        AwareDatetime | None,
        Field(
            description="The date and time the episode was saved.\nTimestamps are returned in ISO 8601 format as Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ.\n"
        ),
    ] = None
    episode: Annotated[
        EpisodeObject | None, Field(description="Information about the episode.")
    ] = None


class PlaylistObject(BaseModel):
    collaborative: Annotated[
        bool | None,
        Field(
            description="`true` if the owner allows other users to modify the playlist.\n"
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description="The playlist description. _Only returned for modified, verified playlists, otherwise_ `null`.\n"
        ),
    ] = None
    external_urls: Annotated[
        ExternalUrlObject | None,
        Field(description="Known external URLs for this playlist.\n"),
    ] = None
    href: Annotated[
        str | None,
        Field(
            description="A link to the Web API endpoint providing full details of the playlist.\n"
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the playlist.\n"
        ),
    ] = None
    images: Annotated[
        list[ImageObject] | None,
        Field(
            description="Images for the playlist. The array may be empty or contain up to three images. The images are returned by size in descending order. See [Working with Playlists](/documentation/web-api/concepts/playlists). _**Note**: If returned, the source URL for the image (`url`) is temporary and will expire in less than a day._\n"
        ),
    ] = None
    name: Annotated[str | None, Field(description="The name of the playlist.\n")] = None
    owner: Annotated[
        PlaylistOwnerObject | None,
        Field(description="The user who owns the playlist\n"),
    ] = None
    public: Annotated[
        bool | None,
        Field(
            description="The playlist's public/private status (if it is added to the user's profile): `true` the playlist is public, `false` the playlist is private, `null` the playlist status is not relevant. For more about public/private status, see [Working with Playlists](/documentation/web-api/concepts/playlists)\n"
        ),
    ] = None
    snapshot_id: Annotated[
        str | None,
        Field(
            description="The version identifier for the current playlist. Can be supplied in other requests to target a specific playlist version\n"
        ),
    ] = None
    items: Annotated[
        PagingPlaylistTrackObject | None,
        Field(
            description="The items of the playlist. _**Note**: This field is only available for playlists owned by the current user or playlists the user is a collaborator of._\n"
        ),
    ] = None
    tracks: Annotated[
        PagingPlaylistTrackObject | None,
        Field(
            deprecated=True,
            description="**Deprecated:** Use `items` instead. The tracks of the playlist.\n",
        ),
    ] = None
    type: Annotated[str | None, Field(description='The object type: "playlist"\n')] = (
        None
    )
    uri: Annotated[
        str | None,
        Field(
            description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the playlist.\n"
        ),
    ] = None


class ShowObject(ShowBase):
    episodes: Annotated[
        PagingSimplifiedEpisodeObject, Field(description="The episodes of the show.\n")
    ]


class AudiobookObject(AudiobookBase):
    chapters: Annotated[
        PagingSimplifiedChapterObject,
        Field(description="The chapters of the audiobook.\n"),
    ]


class PagingSavedTrackObject(PagingObject):
    items: list[SavedTrackObject] | None = None


class PagingSavedEpisodeObject(PagingObject):
    items: list[SavedEpisodeObject] | None = None
